CREATE TABLE contact_t (
	id INT(11) NOT NULL AUTO INCREMENT,
	name VARCHAR(32) NOT NULL,
	message VARCHAR(100) NOT NULL,
	mail_id VARCHAR(32) NOT NULL,
	CONSTRAINT contact_PK PRIMARY KEY (id),
	CONSTRAINT contact_FK FOREIGN KEY
	(mail_id) REFERENCES customer_t(mail_id)
);