CREATE TABLE room_t (
	id INT(11) NOT NULL AUTO INCREMENT,
	name VARCHAR(32) NOT NULL,
	price DOUBLE NOT NULL,
	mail_id VARCHAR(32),
	CONSTRAINT room_PK PRIMARY KEY (id),
	CONSTRAINT room_FK FOREIGN KEY
	(mail_id) REFERENCES customer_t(mail_id)
);